
 
DECLARE 
V_DEPTNO O_DEPT.DEPTNO%TYPE:=&DEPARTMENT_No;
V_DNAME O_DEPT.DNAME%TYPE;
V_LOC   O_DEPT.LOC%TYPE;
V_EMP_NUMBER NUMBER;
V_TOTAL_SALARY O_EMP.SAL%TYPE;
V_SALARY O_EMP.SAL%TYPE;
BEGIN
SELECT DNAME,LOC,(SELECT  NVL(SUM(SAL),0)
                  FROM O_EMP e
                  WHERE   e.DEPTNO=V_DEPTNO)
				  ,(SELECT  COUNT(EMPNO)
                    FROM O_EMP e
                    WHERE   e.DEPTNO=V_DEPTNO)
INTO V_DNAME,V_LOC,V_TOTAL_SALARY ,V_EMP_NUMBER 					  
FROM O_DEPT d
WHERE  d.DEPTNO=V_DEPTNO
GROUP BY DNAME,LOC;
DBMS_OUTPUT.PUT_LINE('Department '|| V_DEPTNO || '('||V_DNAME||') is in '|| V_LOC || ' has ' || V_EMP_NUMBER ||' employee(s) with total salary '|| TRIM(TO_CHAR(V_TOTAL_SALARY,'L99999.99')));
END;
/
